name: 'log_tables'
version: '1.0'

profile: 'log_tables'

source-paths: ["models"]
data-paths: ["data"]

archive:
  - source_schema: public
    target_schema: public
    tables:
      - source_table: users
        target_table: users_log
        updated_at: updated_at
        unique_key: id
